
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8383/eureka/
  instance:
    hostname: localhost
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myhotel
    username : root
    password : root
